version: '3.9'

services:
  web:
    build: .
    command: gunicorn carshop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: carshop
      POSTGRES_USER: carshop_user
      POSTGRES_PASSWORD: strongpassword

volumes:
  postgres_data:
  media_volume:
  static_volume:
  logs_volume: