# Generated by Django 4.2.30 on 2026-09-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Текст сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Видео о компании (ссылка)'),
        ),
        migrations.CreateModel(
            name='CompanyHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='catalog.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'История компании',
                'ordering': ['year'],
            },
        ),
    ]
